export default {
    DRISK_WIDGET_INITIALISED: 'DRISK_WIDGET_INITIALISED', // On initialization of widget
    DRISK_WIDGET_OPEN: 'DRISK_WIDGET_OPEN', // On successfull open
    DRISK_WIDGET_CLOSE_REQUEST: 'DRISK_WIDGET_CLOSE_REQUEST',
    DRISK_WIDGET_CLOSE: 'DRISK_WIDGET_CLOSE', // On widget close
    DRISK_COVER_PURCHASE_SUCCESS: 'DRISK_COVER_PURCHASE_SUCCESS', // On successfull cover purchase
    DRISK_COVER_PURCHASE_FAILED: 'DRISK_COVER_PURCHASE_FAILED',
    DRISK_COVER_CANCELLATION_SUCCESS: 'DRISK_COVER_CANCELLATION_SUCCESS', // On successfull cover purchase
    DRISK_COVER_CANCELLATION_FAILED: 'DRISK_COVER_CANCELLATION_FAILED',
    DRISK_CLAIM_SUCCESS: 'DRISK_CLAIM_SUCCESS', // On successfull cover purchase
    DRISK_CLAIM_FAILED: 'DRISK_CLAIM_FAILED',
}